services:
  frontend:
    image: priyanshuthapliyal/crud_frontend:v2
    ports:
      - 80:80
    depends_on: 
      - backend

  backend:
    image: priyanshuthapliyal/crud_backend:v1
    ports:
      - 3333:3333

    volumes:
      - ./crudapp:/var/lib
volumes:
  todo-mysql-data: