apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 3333
      targetPort: 3333
      nodePort: 30010

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp2
        image: priyanshuthapliyal/crud_backend:v1
        ports:
        - containerPort: 3333

