apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: crudapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploymnet
spec:
  selector:
    matchLabels:
      app: crudapp
  template:
    metadata:
      labels:
        app: crudapp
    spec:
      containers:
      - name: myapp2
        image: priyanshuthapliyal/crud_frontend:v2
        ports:
        - containerPort: 80